// ===========================================================================
// file: lib/database/tables.dart
// purpose: drift table definitions for the local SQLite database.
//          These mirror the Supabase PostgreSQL schema for sync compatibility.
//
// Why drift tables?
//   drift uses these Dart class definitions to:
//   1. Generate the actual SQLite CREATE TABLE statements
//   2. Generate type-safe Dart data classes for each row
//   3. Generate query builders for type-safe CRUD operations
//
// After changing these definitions, run:
//   dart run build_runner build --delete-conflicting-outputs
// ===========================================================================

import 'package:drift/drift.dart';

/// Represents a single journaling session (one conversation).
/// A user triggers the assistant → conversation happens → session closes.
///
/// Think of this like a SQL table definition:
///   CREATE TABLE journal_sessions (
///     session_id TEXT PRIMARY KEY,
///     start_time TEXT NOT NULL,
///     ...
///   );
class JournalSessions extends Table {
  // Client-generated UUID — no server round-trip needed for creation.
  // This is the primary key, set by the app when creating a new session.
  TextColumn get sessionId => text()();

  // When the session started and ended (stored as UTC ISO 8601 text).
  // start_time is always set on creation; end_time is set when session closes.
  DateTimeColumn get startTime => dateTime()();
  DateTimeColumn get endTime => dateTime().nullable()();

  // IANA timezone string (e.g., "America/Denver") for display purposes.
  // Stored so we can show the user what timezone they were in when journaling.
  TextColumn get timezone => text().withDefault(const Constant('UTC'))();

  // AI-generated summary of the session (created on session end).
  // In Phase 1, this is a simple first-sentence extraction.
  // In Phase 3+, this will be Claude-generated.
  TextColumn get summary => text().nullable()();

  // AI-inferred mood tag(s), stored as JSON array string: '["happy","tired"]'
  // Nullable in Phase 1 (no AI tagging). Populated in Phase 3.
  TextColumn get moodTags => text().nullable()();

  // AI-extracted people mentioned, stored as JSON array string: '["Mike","Sarah"]'
  TextColumn get people => text().nullable()();

  // AI-extracted topic/theme tags, stored as JSON array string
  TextColumn get topicTags => text().nullable()();

  // Sync tracking — tracks whether this session has been uploaded to Supabase.
  // Values: 'PENDING' | 'SYNCED' | 'FAILED'
  // In Phase 1, everything stays PENDING (no sync implemented yet).
  TextColumn get syncStatus => text().withDefault(const Constant('PENDING'))();
  DateTimeColumn get lastSyncAttempt => dateTime().nullable()();

  // Whether this session was resumed after being initially ended.
  // Set to true by SessionDao.resumeSession(). Default false for new sessions.
  BoolColumn get isResumed => boolean().withDefault(const Constant(false))();

  // How many times this session has been resumed.
  // Incremented by SessionDao.resumeSession() each time.
  IntColumn get resumeCount => integer().withDefault(const Constant(0))();

  // Standard timestamps — createdAt defaults to current time,
  // updatedAt should be set manually whenever the record is modified.
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt => dateTime().withDefault(currentDateAndTime)();

  // Tell drift which column(s) form the primary key.
  // Using a Set rather than an auto-increment integer because
  // UUIDs are generated client-side for offline-first compatibility.
  @override
  Set<Column> get primaryKey => {sessionId};
}

/// Individual messages within a session (the conversation transcript).
/// Each message is either from the USER, the ASSISTANT, or the SYSTEM.
///
/// Messages are ordered by timestamp within a session to reconstruct
/// the conversation in the correct order.
class JournalMessages extends Table {
  // Client-generated UUID for this message
  TextColumn get messageId => text()();

  // Foreign key to JournalSessions — links this message to its session.
  // The .references() call tells drift about the relationship (for documentation
  // and potential future foreign key enforcement).
  TextColumn get sessionId => text().references(JournalSessions, #sessionId)();

  // Who sent this message.
  // Values: 'USER' | 'ASSISTANT' | 'SYSTEM'
  // USER = typed/spoken by the human
  // ASSISTANT = generated by the journaling agent
  // SYSTEM = internal messages (e.g., session start/end markers)
  TextColumn get role => text()();

  // The actual message content — the text of what was said
  TextColumn get content => text()();

  // When this message was sent (UTC).
  // Used for ordering messages within a session.
  DateTimeColumn get timestamp => dateTime()();

  // How the user entered this message (for analytics/UX decisions).
  // Values: 'TEXT' | 'VOICE'
  // Phase 1 only uses TEXT. Phase 2 adds VOICE via speech_to_text.
  TextColumn get inputMethod => text().withDefault(const Constant('TEXT'))();

  // === Future fields (nullable, populated by AI processing in Phase 3+) ===

  // Named entities extracted from this message (JSON)
  TextColumn get entitiesJson => text().nullable()();

  // Sentiment score (-1.0 to 1.0, nullable)
  RealColumn get sentiment => real().nullable()();

  // Reference to an embedding vector (stored separately or in Supabase pgvector)
  TextColumn get embeddingId => text().nullable()();

  @override
  Set<Column> get primaryKey => {messageId};
}
